apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translation-app
  template:
    metadata:
      labels:
        app: translation-app
        egress.networking.gke.io/enabled: "true"
    spec:
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: translation-app
        image: imagenameplaceholder
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080
        env:
        - name: TRANSLATE_APP_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret-1
              key: TRANSLATE_APP_API_KEY

      imagePullSecrets:
      - name: harbor-secret

