
labels:
- includeSelectors: true
  pairs:
    app-name: web-server

resources:
- deployment.yaml
- service.yaml
- network.yaml

configMapGenerator:
- name: app-configmap-1
  envs:
  - app.properties

replacements:
- source:
    kind: ConfigMap
    name: app-configmap-1
    fieldPath: data.IMAGE
  targets:
  - select:
      kind: Deployment
      name: web-server
    fieldPaths:
    - spec.template.spec.containers.0.image
