apiVersion: v1
kind: Service
metadata:
  name: web-server-test-service
spec:
  type: LoadBalancer 
  selector:
    app: web-server-test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80